services:
  # ----------------------------
  # Load Balancer
  # ----------------------------
  nginx:
    image: nginx:1.27-alpine
    container_name: lb-nginx
    ports:
      - "8088:80" # call ingest-api via http://localhost:8088
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - ingest-api-1
      - ingest-api-2

  # ----------------------------
  # Kafka (KRaft, single-node)
  # ----------------------------
  kafka:
    image: apache/kafka:3.7.0
    container_name: kafka
    ports:
      - "9092:9092"   # optional: host access
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      # single-node safety settings
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

      # your default partitions
      KAFKA_NUM_PARTITIONS: 12
    volumes:
      - kafka_data:/bitnami/kafka

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8089:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    depends_on:
      - kafka

  # ----------------------------
  # Postgres
  # ----------------------------
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=ingestion
      - POSTGRES_USER=ingestion
      - POSTGRES_PASSWORD=ingestion
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # ----------------------------
  # Core services
  # ----------------------------
  ingest-api-1:
    build:
      context: ./services/ingest-api
    container_name: ingest-api-1
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_TOPIC_MAIN=events.ingest.v1
    depends_on:
      - kafka

  ingest-api-2:
    build:
      context: ./services/ingest-api
    container_name: ingest-api-2
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_TOPIC_MAIN=events.ingest.v1
    depends_on:
      - kafka

  event-processor:
    build:
      context: ./services/event-processor
    container_name: event-processor
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_TOPIC_MAIN=events.ingest.v1
      - KAFKA_CONSUMER_GROUP=event-processor-v1
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=ingestion
      - POSTGRES_USER=ingestion
      - POSTGRES_PASSWORD=ingestion
    depends_on:
      - kafka
      - postgres

volumes:
  kafka_data:
  postgres_data:
