server:
  port: 8081

app:
  kafka:
    topic: ${KAFKA_TOPIC_MAIN:events.ingest.v1}
    groupId: ${KAFKA_CONSUMER_GROUP:event-processor-v1}

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    consumer:
      group-id: ${app.kafka.groupId}
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.pk.contracts"
        spring.json.value.default.type: "com.pk.contracts.EventEnvelope"
    listener:
      ack-mode: manual

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:postgres}:${POSTGRES_PORT:5432}/${POSTGRES_DB:ingestion}
    username: ${POSTGRES_USER:ingestion}
    password: ${POSTGRES_PASSWORD:ingestion}

management:
  endpoints:
    web:
      exposure:
        include: health,info

